name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1' # to enable persistent docker cache
    steps:
    - uses: actions/checkout@v2

    - run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - run: make build
    - run: make push

